name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: fetch tokens
        id: doppler
        uses: dopplerhq/secrets-fetch-action@558a97f7f29b80c369cc89e9ecb697c7941dba87
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      - name: setup java and maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: run tests
        run: mvn clean test

      - name: build and scan with sonarqube
        env:
          SONAR_TOKEN: ${{steps.doppler.outputs.SONARQUBE_TOKEN}}
        run: |
         mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
         -Dsonar.java.jdkHome=${{ env.JAVA_HOME }} \
         -Dsonar.host.url=https://sonarcloud.io \
         -Dsonar.organization=adewaleopeloyeru \
         -Dsonar.projectKey=AdewaleOpeloyeru_end-to-end-devops

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: install snyk cli
        run: npm install -g snyk

      - name: snyk scan
        env:
          SNYK_TOKEN: ${{steps.doppler.outputs.SNYK_TOKEN}}
        run: snyk test --all-projects

