name: Create Monitoring Instance and Enable Platform Metrics

on:
  workflow_dispatch:

jobs:
  plan:
    name: plan and review monitoring instance creation
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: fetch tokens
        id: doppler
        uses: dopplerhq/secrets-fetch-action@558a97f7f29b80c369cc89e9ecb697c7941dba87
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@c529327889820530c60b4ce5bbc8d6099e166666
        with:
          terraform_version: 1.13.3

      - name: set terraform cloud token
        run: |
          echo "TF_TOKEN_app_terraform_io=${{ steps.doppler.outputs.TERRAFORM_TOKEN }}" >> $GITHUB_ENV

      - name: terraform init
        run: |
          cd monitoring
          terraform init

      - name: terraform plan
        run: |
          cd monitoring
          terraform plan

  apply:
    name: apply changes
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: fetch tokens
        id: doppler
        uses: dopplerhq/secrets-fetch-action@558a97f7f29b80c369cc89e9ecb697c7941dba87
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@c529327889820530c60b4ce5bbc8d6099e166666
        with:
          terraform_version: 1.13.3

      - name: set terraform cloud token
        run: |
          echo "TF_TOKEN_app_terraform_io=${{ steps.doppler.outputs.TERRAFORM_TOKEN }}" >> $GITHUB_ENV
    
      - name: terraform init
        run: |
          cd monitoring
          terraform init

      - name: terraform apply
        run: |
          cd monitoring
          terraform apply -auto-approve

  enable-platform-metrics:
    name: Enable Platform Metrics
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - name: fetch tokens
        id: doppler
        uses: dopplerhq/secrets-fetch-action@558a97f7f29b80c369cc89e9ecb697c7941dba87
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      - name: install ibmcloud cli
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

      - name: verify ibmcloud cli
        run: ibmcloud --version

      - name: ibmcloud login
        env:
          API_KEY: ${{ steps.doppler.outputs.IBMCLOUD_API_KEY }}
        run: |
          ibmcloud login --apikey ${{ env.API_KEY }} -r eu-gb
          ibmcloud target -g Default
      
      - name: enable platform metrics
        run: ibmcloud resource service-instance-update deployment_monitor --enable-platform-metrics
